# words_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
require 'json'

require 'apimatic_core_interfaces'
require 'apimatic_core'
require 'apimatic_faraday_client_adapter'

require_relative 'words_api/api_helper'
require_relative 'words_api/client'

# Utilities
require_relative 'words_api/utilities/file_wrapper'
require_relative 'words_api/utilities/date_time_helper'

# Http
require_relative 'words_api/http/http_call_back'
require_relative 'words_api/http/http_method_enum'
require_relative 'words_api/http/http_request'
require_relative 'words_api/http/http_response'

# Logger
require_relative 'words_api/logging/configuration/api_logging_configuration'
require_relative 'words_api/logging/sdk_logger'
require_relative 'words_api/http/auth/custom_header_authentication'

# Models
require_relative 'words_api/models/base_model'
require_relative 'words_api/models/definitions_response'
require_relative 'words_api/models/examples_response'
require_relative 'words_api/models/pronunciation_details'
require_relative 'words_api/models/synonyms_response'
require_relative 'words_api/models/frequency_response'
require_relative 'words_api/models/word_details'
require_relative 'words_api/models/word_response'
require_relative 'words_api/models/pronunciation_response'
require_relative 'words_api/models/frequency_details'
require_relative 'words_api/models/syllable_details'

# Exceptions
require_relative 'words_api/exceptions/api_exception'

require_relative 'words_api/configuration'

# Controllers
require_relative 'words_api/controllers/base_controller'
require_relative 'words_api/controllers/ap_is_controller'
