# words_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WordsApi
  # This custom type contains response for frequency endpoint.
  class FrequencyResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The word that is searched.
    # @return [String]
    attr_accessor :word

    # This model contains frequency details of a specific word.
    # @return [FrequencyDetails]
    attr_accessor :frequency

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['word'] = 'word'
      @_hash['frequency'] = 'frequency'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(word = nil, frequency = nil)
      @word = word
      @frequency = frequency
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      word = hash.key?('word') ? hash['word'] : nil
      frequency = FrequencyDetails.from_hash(hash['frequency']) if hash['frequency']

      # Create object from extracted values.
      FrequencyResponse.new(word,
                            frequency)
    end
  end
end
