# words_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WordsApi
  # This model contains frequency details of a specific word.
  class FrequencyDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Explains the zipf score.
    # @return [Float]
    attr_accessor :zipf

    # Explains the perMillion score.
    # @return [Float]
    attr_accessor :per_million

    # Explains the diversity score.
    # @return [Float]
    attr_accessor :diversity

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['zipf'] = 'zipf'
      @_hash['per_million'] = 'perMillion'
      @_hash['diversity'] = 'diversity'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(zipf = nil, per_million = nil, diversity = nil)
      @zipf = zipf
      @per_million = per_million
      @diversity = diversity
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      zipf = hash.key?('zipf') ? hash['zipf'] : nil
      per_million = hash.key?('perMillion') ? hash['perMillion'] : nil
      diversity = hash.key?('diversity') ? hash['diversity'] : nil

      # Create object from extracted values.
      FrequencyDetails.new(zipf,
                           per_million,
                           diversity)
    end
  end
end
