# words_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WordsApi
  # This model contains pronunciation details of a specific word.
  class PronunciationDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The pronunciation of the word.
    # @return [String]
    attr_accessor :all

    # The noun pronunciation of the word.
    # @return [String]
    attr_accessor :noun

    # The verb pronunciation of the word.
    # @return [String]
    attr_accessor :verb

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['all'] = 'all'
      @_hash['noun'] = 'noun'
      @_hash['verb'] = 'verb'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        noun
        verb
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(all = nil, noun = SKIP, verb = SKIP)
      @all = all
      @noun = noun unless noun == SKIP
      @verb = verb unless verb == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      all = hash.key?('all') ? hash['all'] : nil
      noun = hash.key?('noun') ? hash['noun'] : SKIP
      verb = hash.key?('verb') ? hash['verb'] : SKIP

      # Create object from extracted values.
      PronunciationDetails.new(all,
                               noun,
                               verb)
    end
  end
end
