# words_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WordsApi
  # This custom type contains the syllable details for word API.
  class SyllableDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The count of syllables.
    # @return [Integer]
    attr_accessor :count

    # The list of syllables.
    # @return [Array[String]]
    attr_accessor :list

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['count'] = 'count'
      @_hash['list'] = 'list'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        count
        list
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(count = SKIP, list = SKIP)
      @count = count unless count == SKIP
      @list = list unless list == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      count = hash.key?('count') ? hash['count'] : SKIP
      list = hash.key?('list') ? hash['list'] : SKIP

      # Create object from extracted values.
      SyllableDetails.new(count,
                          list)
    end
  end
end
