# words_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WordsApi
  # Utility class for custom header authorization.
  class CustomHeaderAuthentication < CoreLibrary::HeaderAuth
    # Display error message on occurrence of authentication failure.
    # @returns [String] The oAuth error message.
    def error_message
      'CustomHeaderAuthentication: x_rapid_api_key is undefined.'
    end

    # Initialization constructor.
    def initialize(custom_header_authentication_credentials)
      auth_params = {}
      auth_params['X-RapidAPI-Key'] = custom_header_authentication_credentials.x_rapid_api_key unless
        custom_header_authentication_credentials.nil? || custom_header_authentication_credentials.x_rapid_api_key.nil?

      super auth_params
    end
  end

  # Data class for CustomHeaderAuthenticationCredentials.
  # Data class for CustomHeaderAuthenticationCredentials.
  class CustomHeaderAuthenticationCredentials
    attr_reader :x_rapid_api_key

    def initialize(x_rapid_api_key:)
      raise ArgumentError, 'x_rapid_api_key cannot be nil' if x_rapid_api_key.nil?

      @x_rapid_api_key = x_rapid_api_key
    end

    def clone_with(x_rapid_api_key: nil)
      x_rapid_api_key ||= self.x_rapid_api_key

      CustomHeaderAuthenticationCredentials.new(
        x_rapid_api_key: x_rapid_api_key
      )
    end
  end
end
